name = "vst3ada"
description = "A VST3 API implementation in Pure Ada"
version = "0.1.0-dev"

authors = ["Edward Gallyot"]
maintainers = ["Edward Gallyot <edgallyot@gmail.com>"]
maintainers-logins = ["edwardgallyot"]

configuration = { disabled = true}
